### PR TITLE
fix: match the character name against each words of all messages

### LINKED ISSUE #45: Bot react to characters within words
# What happens

Given a character (example `lac`) the bot will answer to words that contains that character (like `J'ai une belle cadillac`)

# What should happen

The bot should ignore those sentences

### PR DESCRIPTION
**Pull request by sarlam**
vereslesblaise -> false
vers les blaiseries -> false
blaise -> true
pere blaise -> true
ceciESTuNBlaise -> false
voila le pere blaise qui passe -> true

close #45

### CODE REVIEW

File: characters/characters.go [hunk 1]
```diff
@@ -89,18 +89,22 @@ func MakeCharactersSliceFromFolder(folder string) ([]Character, error) {
 	return characters, nil
 }
 
-// TryGetQuoteFromMessage returns a random quote from a character if its name is found in the message
+// GetQuoteFromMessage returns a random quote from a character if its name is found in the message
 func GetQuoteFromMessage(characters []Character, message string) (string, error) {
 	for _, character := range characters {
-		if strings.Index(strings.ToUpper(message), strings.ToUpper(character.Name)) > -1 {
+		upperCaseMessage := strings.Split(strings.ToUpper(message), " ")
```
Comment (Terag) [inline characters/characters.go:95]: Better !

**Review by Terag — APPROVED** [review]
